apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-api
  template:
    metadata:
      labels:
        app: database-api
    spec:
      containers:
        - name: database-api
          image: us.icr.io/sn-labs-thiwankalaks/nodeapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: database-api
spec:
  selector:
    app: database-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
